const school_names = [
  "Adelphi",
  "Albany",
  "American",
  "App State",
  "Appalachian State University",
  "Arizona State University",
  "Auburn University",
  "Ball State",
  "Baylor",
  "Bentley",
  "Berkeley",
  "Bloomsburg",
  "Boise",
  "Boise State",
  "Boston",
  "Boulder",
  "Bowling Green",
  "Bucknell",
  "Buffalo",
  "Butler University",
  "Cal Poly Pomona",
  "Cal Poly Slo",
  "Carnegie Mellon",
  "Central Missouri",
  "Chapman",
  "Charleston",
  "Chico State",
  "Christopher Newport University",
  "Cincinnati",
  "Clemson University",
  "CMU",
  "Colgate",
  "Columbia",
  "Connecticut",
  "Cornell",
  "Cortland",
  "Creighton",
  "CSUF",
  "CSULB",
  "CSUN",
  "CSUSM",
  "Dartmouth",
  "Davis",
  "DePaul University",
  "DePauw University",
  "Detroit Mercy",
  "Drexel",
  "Duke University",
  "Duquesne",
  "East Bay",
  "East Carolina",
  "Eastern Illinois",
  "Eastern Washington",
  "ECU",
  "Elmhurst",
  "Elon",
  "Emory",
  "EMU",
  "FAU",
  "Florida Atlantic",
  "Florida Tech",
  "Frankin&Marshall",
  "Fresno State",
  "FSU",
  "George Mason",
  "GCSU",
  "Georgia College",
  "Georgia Tech",
  "GMU",
  "Grand Valley",
  "Grand Valley State",
  "GVSU",
  "Hartford",
  "Hartwick",
  "Harvard",
  "Hawaii",
  "High Point",
  "Hofstra",
  "Hope College",
  "Idaho",
  "Illinois State",
  "Indiana University",
  "Iona",
  "Iona College",
  "Iowa State",
  "Irvine",
  "James Madison University",
  "Johns Hopkins",
  "Kansas State University",
  "Kelly",
  "Kennesaw State University",
  "Kent State",
  "La Crosse",
  "Lafayette",
  "Lehigh University",
  "Lindenwood",
  "LMU",
  "Marquette",
  "Miami University",
  "Michigan State University",
  "Missouri State",
  "Mizzou",
  "Monmouth University",
  "Montclair",
  "MTSU",
  "Nebraska",
  "North Carolina State University",
  "North Dakota",
  "Northern Arizona University",
  "Northern Illinois",
  "Northwest Missouri",
  "Northwestern",
  "NW Missouri",
  "Ohio State University",
  "Oklahoma City",
  "Old Dominion",
  "Ole Miss",
  "Oregon",
  "Oregon State",
  "Others",
  "Pace",
  "Penn State University",
  "Pepperdine",
  "Pittsburgh",
  "Pomona",
  "Princeton",
  "Puget Sound",
  "Purdue",
  "Quinnipiac",
  "Radford",
  "Redlands",
  "Rhode Island",
  "Rochester",
  "Rollins",
  "Rowan",
  "Rutgers",
  "Sac State",
  "Sacramento",
  "Sacramento State",
  "Sacred Heart",
  "San Luis Obispo",
  "School of Mines",
  "SDSU",
  "Seton Hall",
  "SFSU",
  "SIUE",
  "SJSU",
  "Sonoma State",
  "South Dakota",
  "Southern Illinois",
  "Southern Methodist University",
  "Southern Utah University",
  "St. John",
  "St. Joseph",
  "St. Louis",
  "Stanford",
  "Stetson",
  "Stevens Institute of Technology",
  "Stockton",
  "SUNY Cortland",
  "SUNY Oswego",
  "SUU",
  "Syracuse University",
  "TCNJ",
  "Temple University",
  "Tennessee",
  "Tennessee Chattanooga",
  "The University of Arizona",
  "The University of Iowa",
  "The University of Oklahoma",
  "The University of Texas",
  "The University of Utah",
  "Toronto",
  "Towson",
  "TSU",
  "Tufts",
  "Tulane",
  "UBC",
  "UC Davis",
  "UC Irvine",
  "UC Riverside",
  "UCI",
  "UCLA",
  "UCM",
  "UConn",
  "UCR",
  "UCSB",
  "UCSD",
  "UF",
  "UIUC",
  "UMass",
  "UNCO",
  "UNCW",
  "UNF",
  "UNH",
  "Union College",
  "University of Alabama",
  "University of Central Florida",
  "University of Central Missouri",
  "University of Dayton",
  "University of Delaware",
  "University of Denver",
  "University of Florida",
  "University of Georgia",
  "University of Illinois",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Nevada",
  "University of New Hampshire",
  "University of North Carolina",
  "University of Northern Colorado",
  "University of Pennsylvania",
  "University of Rhode Island",
  "University of South Carolina",
  "University Of Tampa",
  "University of the Pacific",
  "University of Wisconsin",
  "UNLV",
  "USC",
  "USD",
  "UTC",
  "UTK",
  "UW",
  "UW - La Criosse",
  "VCU",
  "Villanova",
  "Virginia Tech",
  "Wake Forest University",
  "Washington",
  "Washington University",
  "WashU",
  "WCU",
  "West Chester",
  "West Virginia University",
  "Western Kentucky",
  "Western Michigan University",
  "Widener",
  "William Woods",
  "William&Mary",
  "Wittenburg",
  "WKU",
  "WLU",
  "WSU",
  "Yale",
  "Uwash",
];

export default school_names;
